spring:
  profiles:
    active:
      - dev
  #  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/funnyshare?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: "root"
#    password: "root"
#    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
funnyshare:
  upload-path: uploads-test
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:./funnyshare-prod
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
funnyshare:
  upload-path: uploads-test
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:funnyshare-dev
funnyshare:
  upload-path: uploads-dev
---
spring:
  config:
    activate:
      on-profile: test
funnyshare:
  upload-path: uploads-test